### ISSUE TITLE
`BuiltConditionExpression` has the wrong type

### ISSUE THREAD

**Issue by tibbe** [youtype/mypy_boto3_builder#190]
**Describe the bug**
The `BuiltConditionExpression` type is defined in `dynamodb.conditions` as

```py
BuiltConditionExpression = NamedTuple(
    "BuiltConditionExpression",
    [
        ("condition_expression", str),
        ("attribute_name_placeholders", List[str]),
        ("attribute_value_placeholders", Dict[str, Any]),
    ],
)
```

but it should be

```py
BuiltConditionExpression = NamedTuple(
    "BuiltConditionExpression",
    [
        ("condition_expression", str),
        ("attribute_name_placeholders", Dict[str, str]),
        ("attribute_value_placeholders", Dict[str, Any]),
    ],
)
```

`attribute_name_placeholders` corresponds to the `"ExpressionAttributeNames"` field of type `QueryInputTableQueryTypeDef`, which has type `Mapping[str, str]`. This is also documented in https://github.com/boto/boto3/blob/129affc170a7827b5848062060c93a5ca48558e0/boto3/dynamodb/conditions.py#L337.

**To Reproduce**

Use `BuiltConditionExpression` to build an expression and try to pass it to `boto3.client('dynamodb').query(...)`.

**Additional context**

```toml
boto3 = "1.26.93"
botocore = "1.29.93"
boto3-stubs = {version = "1.26.93", extras = ["apigatewaymanagementapi", "cloudsearch", "cloudsearchdomain", "cognito-idp", "dynamodb", "s3", "secretsmanager", "ses", "sns", "sqs", "transcribe", "translate"]}
```
