### ISSUE TITLE
Type error after upgrading `aioboto3` and `types-aioboto3[s3]` to 13.3.0

### ISSUE THREAD

**Issue by HazyFish** [youtype/mypy_boto3_builder#342]
**Describe the bug**
Type error after upgrading `aioboto3` and `types-aioboto3[s3]` to 13.3.0. The error didn't exist before.

**To Reproduce**

1. Install deps using PDM (see `pyproject.toml` snippet below)
2. Run `pyright` on the following code sample

```python
from aioboto3 import Session
from types_aiobotocore_s3 import S3Client

async def f():
    async with Session().client("s3") as s3:
        s3: S3Client
...
```

**Actual output**

```
error: Type "AioBaseClient" is not assignable to declared type "S3Client"
  "AioBaseClient" is not assignable to "S3Client" (reportAssignmentType)
```

**Expected output**

No error

**Additional context**

```toml
[project]
dependencies = [
    "aioboto3>=13.3.0",
    "types-aioboto3[s3]>=13.3.0.post1",
]
requires-python = "==3.12.*"
```
